package org.szte.wsn.downloader2;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DataMsg'
 * message type.
 */

public class DataMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 23;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 99;

    /** Create a new DataMsg of size 23. */
    public DataMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DataMsg of the given data_length. */
    public DataMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg with the given data_length
     * and base offset.
     */
    public DataMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store.
     */
    public DataMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DataMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DataMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg embedded in the given message
     * at the given base offset.
     */
    public DataMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DataMsg embedded in the given message
     * at the given base offset and length.
     */
    public DataMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DataMsg> \n";
      try {
        s += "  [source=0x"+Long.toHexString(get_source())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [address=0x"+Long.toHexString(get_address())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqnum=0x"+Long.toHexString(get_seqnum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [payload=";
        for (int i = 0; i < 16; i++) {
          s += "0x"+Long.toHexString(getElement_payload(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: source
    //   Field type: int, signed
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'source' is signed (true).
     */
    public static boolean isSigned_source() {
        return true;
    }

    /**
     * Return whether the field 'source' is an array (false).
     */
    public static boolean isArray_source() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'source'
     */
    public static int offset_source() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'source'
     */
    public static int offsetBits_source() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'source'
     */
    public int get_source() {
        return (int)getUIntBEElement(offsetBits_source(), 16);
    }

    /**
     * Set the value of the field 'source'
     */
    public void set_source(int value) {
        setUIntBEElement(offsetBits_source(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'source'
     */
    public static int size_source() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'source'
     */
    public static int sizeBits_source() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: address
    //   Field type: long, signed
    //   Offset (bits): 16
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'address' is signed (true).
     */
    public static boolean isSigned_address() {
        return true;
    }

    /**
     * Return whether the field 'address' is an array (false).
     */
    public static boolean isArray_address() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'address'
     */
    public static int offset_address() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'address'
     */
    public static int offsetBits_address() {
        return 16;
    }

    /**
     * Return the value (as a long) of the field 'address'
     */
    public long get_address() {
        return (long)getUIntBEElement(offsetBits_address(), 32);
    }

    /**
     * Set the value of the field 'address'
     */
    public void set_address(long value) {
        setUIntBEElement(offsetBits_address(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'address'
     */
    public static int size_address() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'address'
     */
    public static int sizeBits_address() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqnum
    //   Field type: short, signed
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqnum' is signed (true).
     */
    public static boolean isSigned_seqnum() {
        return true;
    }

    /**
     * Return whether the field 'seqnum' is an array (false).
     */
    public static boolean isArray_seqnum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqnum'
     */
    public static int offset_seqnum() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqnum'
     */
    public static int offsetBits_seqnum() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'seqnum'
     */
    public short get_seqnum() {
        return (short)getUIntBEElement(offsetBits_seqnum(), 8);
    }

    /**
     * Set the value of the field 'seqnum'
     */
    public void set_seqnum(short value) {
        setUIntBEElement(offsetBits_seqnum(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqnum'
     */
    public static int size_seqnum() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqnum'
     */
    public static int sizeBits_seqnum() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: payload
    //   Field type: byte[], signed
    //   Offset (bits): 56
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'payload' is signed (true).
     */
    public static boolean isSigned_payload() {
        return true;
    }

    /**
     * Return whether the field 'payload' is an array (true).
     */
    public static boolean isArray_payload() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'payload'
     */
    public static int offset_payload(int index1) {
        int offset = 56;
        if (index1 < 0 || index1 >= 16) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'payload'
     */
    public static int offsetBits_payload(int index1) {
        int offset = 56;
        if (index1 < 0 || index1 >= 16) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'payload' as a byte[]
     */
    public byte[] get_payload() {
        byte[] tmp = new byte[16];
        for (int index0 = 0; index0 < numElements_payload(0); index0++) {
            tmp[index0] = getElement_payload(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'payload' from the given byte[]
     */
    public void set_payload(byte[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_payload(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a byte) of the array 'payload'
     */
    public byte getElement_payload(int index1) {
        return (byte)getSIntBEElement(offsetBits_payload(index1), 8);
    }

    /**
     * Set an element of the array 'payload'
     */
    public void setElement_payload(int index1, byte value) {
        setSIntBEElement(offsetBits_payload(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'payload'
     */
    public static int totalSize_payload() {
        return (128 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'payload'
     */
    public static int totalSizeBits_payload() {
        return 128;
    }

    /**
     * Return the size, in bytes, of each element of the array 'payload'
     */
    public static int elementSize_payload() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'payload'
     */
    public static int elementSizeBits_payload() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'payload'
     */
    public static int numDimensions_payload() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'payload'
     */
    public static int numElements_payload() {
        return 16;
    }

    /**
     * Return the number of elements in the array 'payload'
     * for the given dimension.
     */
    public static int numElements_payload(int dimension) {
      int array_dims[] = { 16,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'payload' with a String
     */
    public void setString_payload(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_payload(i, (byte)s.charAt(i));
         }
         setElement_payload(i, (byte)0); //null terminate
    }

    /**
     * Read the array 'payload' as a String
     */
    public String getString_payload() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,16)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_payload(i) == (char)0) break;
             carr[i] = (char)getElement_payload(i);
         }
         return new String(carr,0,i);
    }

}
