			if(TOS_NODE_ID==1){
				settings[0].work=SEND_SYNC;
				settings[1].work=TX1;
				settings[2].work=TX1;
				settings[3].work=RX;
				settings[4].work=RECV_SYNC;
				settings[5].work=TX1;
				settings[6].work=TX1;
				settings[7].work=RX;
				settings[8].work=RECV_SYNC;
				settings[9].work=TX1;
				settings[10].work=TX1;
				settings[11].work=RX;
				settings[12].work=RECV_SYNC;
				settings[13].work=RX;
				settings[14].work=RX;
				settings[15].work=RX;
				settings[16].work=DEBUG;
				settings[17].work=NO_DEBUG;
				settings[18].work=NO_DEBUG;
				settings[19].work=NO_DEBUG;
			}
			if(TOS_NODE_ID==2){
				settings[0].work=RECV_SYNC;
				settings[1].work=RX;
				settings[2].work=RX;
				settings[3].work=RX;
				settings[4].work=SEND_SYNC;
				settings[5].work=TX2;
				settings[6].work=RX;
				settings[7].work=TX1;
				settings[8].work=RECV_SYNC;
				settings[9].work=TX2;
				settings[10].work=RX;
				settings[11].work=TX1;
				settings[12].work=RECV_SYNC;
				settings[13].work=TX1;
				settings[14].work=TX1;
				settings[15].work=RX;
				settings[16].work=DEBUG;
				settings[17].work=DEBUG;
				settings[18].work=DEBUG;
				settings[19].work=DEBUG;
			}
			if(TOS_NODE_ID==3){
				settings[0].work=RECV_SYNC;
				settings[1].work=TX2;
				settings[2].work=RX;
				settings[3].work=TX1;
				settings[4].work=RECV_SYNC;
				settings[5].work=RX;
				settings[6].work=RX;
				settings[7].work=RX;
				settings[8].work=SEND_SYNC;
				settings[9].work=RX;
				settings[10].work=TX2;
				settings[11].work=TX2;
				settings[12].work=RECV_SYNC;
				settings[13].work=TX2;
				settings[14].work=RX;
				settings[15].work=TX1;
				settings[16].work=DEBUG;
				settings[17].work=DEBUG;
				settings[18].work=DEBUG;
				settings[19].work=DEBUG;
			}
			if(TOS_NODE_ID==4){
				settings[0].work=RECV_SYNC;
				settings[1].work=RX;
				settings[2].work=TX2;
				settings[3].work=TX2;
				settings[4].work=RECV_SYNC;
				settings[5].work=RX;
				settings[6].work=TX2;
				settings[7].work=TX2;
				settings[8].work=RECV_SYNC;
				settings[9].work=RX;
				settings[10].work=RX;
				settings[11].work=RX;
				settings[12].work=SEND_SYNC;
				settings[13].work=RX;
				settings[14].work=TX2;
				settings[15].work=TX2;
				settings[16].work=DEBUG;
				settings[17].work=DEBUG;
				settings[18].work=DEBUG;
				settings[19].work=DEBUG;
			}
