/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RssiDoneMsg'
 * message type.
 */

public class RssiDoneMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 0;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 12;

    /** Create a new RssiDoneMsg of size 0. */
    public RssiDoneMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RssiDoneMsg of the given data_length. */
    public RssiDoneMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiDoneMsg with the given data_length
     * and base offset.
     */
    public RssiDoneMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiDoneMsg using the given byte array
     * as backing store.
     */
    public RssiDoneMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiDoneMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RssiDoneMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiDoneMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RssiDoneMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiDoneMsg embedded in the given message
     * at the given base offset.
     */
    public RssiDoneMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiDoneMsg embedded in the given message
     * at the given base offset and length.
     */
    public RssiDoneMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RssiDoneMsg> \n";
      return s;
    }

    // Message-type-specific access methods appear below.

}
