#ifndef __INFRASTRUCTURESETTINGS_H__
#define __INFRASTRUCTURESETTINGS_H__

enum {
	TX1 = 0, //sendWave 1
	TX1A = TX1,
	TX2 = 1, //sendWave 2
	TX2A = TX2,
	RX = 2, //sampleRSSI
	RXA = RX,
	SSYN=3, //sends sync message
	RSYN=4, //waits for sync message
	DEB = 5,
	NTRX = 6,
	NDEB = 7,
	W1 = 8,
	W10 = 9,
	W100 = 10,
	DSYN = 11,
	WCAL = 12,
	TX1B = 13,
	TX2B = 14,
	RXB = 15,
};

#define FOUR_MOTE 2
#define FOUR_MOTE_WF 3
#define PHASEMAP_TEST_13 4
#define PHASEMAP_TEST_18 5
#define PROCESSING_DEBUG 6
#define PHASEMAP_TEST_4 7
#define FOURTEEN_MOTE_WF 8
#define PHASEMAP_TEST_6 9
#define PHASEMAP_TEST_12 10
#define PHASEMAP_TEST_5 11
#define SIX_MOTE 12
#define LOC_TEST_9_GRID 13
#define LOC_4TX_4ANCHORRX 14
#define PHASEMAP_TEST_8 15
#define MULT_RX_1 16
#define SCHEDULER_AND_RSSI_LOC_TESTER 17
#define COMPETITION 18
#define FIVE_MOTE_AB 19

#ifndef MEASURE_TYPE
#error "Please define MEASURE_TYPE"
#elif MEASURE_TYPE==0
#error "Unknown MEASURE_TYPE"
#endif

#if MEASURE_TYPE == FOUR_MOTE
	#define NUMBER_OF_INFRAST_NODES 4
	#define NUMBER_OF_SLOTS 16
	#define NUMBER_OF_RX 6
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//  0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15
		{SSYN,  TX1,   RX,   RX, RSYN,  TX1,   RX,   RX, RSYN,  TX1,   RX,   RX, RSYN,  TX1,  TX1,  TX1},
		{RSYN,  TX2,  TX1,  TX1, SSYN,   RX,  TX1,   RX, RSYN,   RX,  TX1,   RX, RSYN,  TX2,   RX,   RX},
		{RSYN,   RX,  TX2,   RX, RSYN,  TX2 , TX2 , TX1, SSYN,   RX,   RX,  TX1, RSYN,   RX,  TX2,   RX},
		{RSYN,   RX,   RX,  TX2, RSYN,   RX,   RX,  TX2, RSYN,  TX2,  TX2,  TX2, SSYN,   RX,   RX,  TX2}
	};
#elif MEASURE_TYPE == FOUR_MOTE_WF
	#define NUMBER_OF_INFRAST_NODES 4
	#define NUMBER_OF_SLOTS 24
	#define NUMBER_OF_RX 6
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//  0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23
		{SSYN,  TX1,   RX,   RX, RSYN,  TX1,   RX,   RX, RSYN,  TX1,   RX,   RX, RSYN,  TX1,  TX1,  TX1, DSYN,  DEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{RSYN,  TX2,  TX1,  TX1, SSYN,   RX,  TX1,   RX, RSYN,   RX,  TX1,   RX, RSYN,  TX2,   RX,   RX, RSYN, NDEB, DSYN,  DEB, RSYN, NDEB, RSYN, NDEB},
		{RSYN,   RX,  TX2,   RX, RSYN,  TX2 , TX2 , TX1, SSYN,   RX,   RX,  TX1, RSYN,   RX,  TX2,   RX, RSYN, NDEB, RSYN, NDEB, DSYN,  DEB, RSYN, NDEB},
		{RSYN,   RX,   RX,  TX2, RSYN,   RX,   RX,  TX2, RSYN,  TX2,  TX2,  TX2, SSYN,   RX,   RX,  TX2, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, DSYN,  DEB}
	};
#elif MEASURE_TYPE == SIX_MOTE
	#define NUMBER_OF_INFRAST_NODES 6
	#define NUMBER_OF_SLOTS 42
	#define NUMBER_OF_RX 20
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//    0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    25    26    27    28    29    30    31    32    33    34    35    36    37    38    39    40    41
		{  SSYN,  TX1,   RX,   RX,   RX,   RX,   W1, RSYN,  TX1,   RX,   RX,   RX,   RX,   W1, RSYN,  TX1,   RX,   RX,   RX,   RX,   W1, RSYN,  TX1,   RX,   RX,   RX,   RX,   W1, RSYN,  TX1,   RX,   RX,   RX,   RX,   W1, RSYN,  TX2,  TX2,  TX2,  TX2,  TX2,   W1},
		{  RSYN,  TX2,  TX1,  TX1,  TX1,  TX1,   W1, SSYN,   RX,  TX2,   RX,   RX,   RX,   W1, RSYN,   RX,  TX2,   RX,   RX,   RX,   W1, RSYN,   RX,  TX2,   RX,   RX,   RX,   W1, RSYN,   RX,  TX2,   RX,   RX,   RX,   W1, RSYN,  TX1,   RX,   RX,   RX,   RX,   W1},
		{  RSYN,   RX,  TX2,   RX,   RX,   RX,   W1, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1,   W1, SSYN,   RX,   RX,  TX2,   RX,   RX,   W1, RSYN,   RX,   RX,  TX2,   RX,   RX,   W1, RSYN,   RX,   RX,  TX2,   RX,   RX,   W1, RSYN,   RX,  TX1,   RX,   RX,   RX,   W1},
		{  RSYN,   RX,   RX,  TX2,   RX,   RX,   W1, RSYN,   RX,   RX,  TX2,   RX,   RX,   W1, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1,   W1, SSYN,   RX,   RX,   RX,  TX2,   RX,   W1, RSYN,   RX,   RX,   RX,  TX2,   RX,   W1, RSYN,   RX,   RX,  TX1,   RX,   RX,   W1},
		{  RSYN,   RX,   RX,   RX,  TX2,   RX,   W1, RSYN,   RX,   RX,   RX,  TX2,   RX,   W1, RSYN,   RX,   RX,   RX,  TX2,   RX,   W1, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1,   W1, SSYN,   RX,   RX,   RX,   RX,  TX2,   W1, RSYN,   RX,   RX,   RX,  TX1,   RX,   W1},
		{  RSYN,   RX,   RX,   RX,   RX,  TX2,   W1, RSYN,   RX,   RX,   RX,   RX,  TX2,   W1, RSYN,   RX,   RX,   RX,   RX,  TX2,   W1, RSYN,   RX,   RX,   RX,   RX,  TX2,   W1, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1,   W1, SSYN,   RX,   RX,   RX,   RX,  TX1,   W1}
	};
#elif MEASURE_TYPE == SIX_MOTE_WF
	#define NUMBER_OF_INFRAST_NODES 6
	#define NUMBER_OF_SLOTS 48
	#define NUMBER_OF_RX 20
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//    0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    25    26    27    28    29    30    31    32    33    34    35    36    37    38    39    40    41    42    43    44    45    46    47
		{  SSYN,  TX1,   RX,   RX,   RX,   RX, RSYN,  TX1,   RX,   RX,   RX,   RX, RSYN,  TX1,   RX,   RX,   RX,   RX, RSYN,  TX1,   RX,   RX,   RX,   RX, RSYN,  TX1,   RX,   RX,   RX,   RX, RSYN,  TX2,  TX2,  TX2,  TX2,  TX2, DSYN,  DEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{  RSYN,  TX2,  TX1,  TX1,  TX1,  TX1, SSYN,   RX,  TX2,   RX,   RX,   RX, RSYN,   RX,  TX2,   RX,   RX,   RX, RSYN,   RX,  TX2,   RX,   RX,   RX, RSYN,   RX,  TX2,   RX,   RX,   RX, RSYN,  TX1,   RX,   RX,   RX,   RX, RSYN, NDEB, DSYN,  DEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{  RSYN,   RX,  TX2,   RX,   RX,   RX, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1, SSYN,   RX,   RX,  TX2,   RX,   RX, RSYN,   RX,   RX,  TX2,   RX,   RX, RSYN,   RX,   RX,  TX2,   RX,   RX, RSYN,   RX,  TX1,   RX,   RX,   RX, RSYN, NDEB, RSYN, NDEB, DSYN,  DEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{  RSYN,   RX,   RX,  TX2,   RX,   RX, RSYN,   RX,   RX,  TX2,   RX,   RX, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1, SSYN,   RX,   RX,   RX,  TX2,   RX, RSYN,   RX,   RX,   RX,  TX2,   RX, RSYN,   RX,   RX,  TX1,   RX,   RX, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, DSYN,  DEB, RSYN, NDEB, RSYN, NDEB},
		{  RSYN,   RX,   RX,   RX,  TX2,   RX, RSYN,   RX,   RX,   RX,  TX2,   RX, RSYN,   RX,   RX,   RX,  TX2,   RX, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1, SSYN,   RX,   RX,   RX,   RX,  TX2, RSYN,   RX,   RX,   RX,  TX1,   RX, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, DSYN,  DEB, RSYN, NDEB},
		{  RSYN,   RX,   RX,   RX,   RX,  TX2, RSYN,   RX,   RX,   RX,   RX,  TX2, RSYN,   RX,   RX,   RX,   RX,  TX2, RSYN,   RX,   RX,   RX,   RX,  TX2, RSYN,  TX2,  TX1,  TX1,  TX1,  TX1, SSYN,   RX,   RX,   RX,   RX,  TX1, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, DSYN,  DEB}
	};
#elif MEASURE_TYPE == PHASEMAP_TEST_13_DEB
	#define NUMBER_OF_INFRAST_NODES 13
	#define NUMBER_OF_SLOTS 34
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    25    26    27    28    29    30    31    32    33
		{ RSYN,  TX1,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,  TX2,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ SSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB, RSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB, DSYN, NDEB},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN, NDEB, RSYN,  DEB}
	};
#elif MEASURE_TYPE == PHASEMAP_TEST_18
	#define NUMBER_OF_INFRAST_NODES 18
	#define NUMBER_OF_SLOTS 18
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17
		{ RSYN,  TX1,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,  TX2,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ SSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN}
	};
#elif MEASURE_TYPE == PHASEMAP_TEST_12
	#define NUMBER_OF_INFRAST_NODES 12
	#define NUMBER_OF_SLOTS 12
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5     6     7     8     9    10    11
		{ RSYN,  TX1,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,  TX2,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ SSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN}
	};
#elif MEASURE_TYPE == PHASEMAP_TEST_8
	#define NUMBER_OF_INFRAST_NODES 8
	#define NUMBER_OF_SLOTS 9
	#define NUMBER_OF_RX 2
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5
		{ RSYN,  TX1,  TX1,  W10, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,  TX2,  TX2,  W10, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ SSYN,   RX,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,   RX,  W10, SSYN, RSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,   RX,  W10, RSYN, SSYN, RSYN, RSYN, RSYN},
		{ RSYN,   RX,   RX,  W10, RSYN, RSYN, SSYN, RSYN, RSYN},
		{ RSYN,   RX,   RX,  W10, RSYN, RSYN, RSYN, SSYN, RSYN},
		{ RSYN,   RX,   RX,  W10, RSYN, RSYN, RSYN, RSYN, SSYN}
	};
//elfelejtettem melyik kell, amiben 2 vagy amiben 3 meres van	
//#elif MEASURE_TYPE == PHASEMAP_TEST_8
//	#define NUMBER_OF_INFRAST_NODES 8
//	#define NUMBER_OF_SLOTS 10
//	#define NUMBER_OF_RX 3
//	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
//		//   0     1     2     3     4     5
//		{ RSYN,  TX1,  TX1,  TX1,  W10, RSYN, RSYN, RSYN, RSYN, RSYN},
//		{ RSYN,  TX2,  TX2,  TX2,  W10, RSYN, RSYN, RSYN, RSYN, RSYN},
//		{ SSYN,   RX,   RX,   RX,  W10, RSYN, RSYN, RSYN, RSYN, RSYN},
//		{ RSYN,   RX,   RX,   RX,  W10, SSYN, RSYN, RSYN, RSYN, RSYN},
//		{ RSYN,   RX,   RX,   RX,  W10, RSYN, SSYN, RSYN, RSYN, RSYN},
//		{ RSYN,   RX,   RX,   RX,  W10, RSYN, RSYN, SSYN, RSYN, RSYN},
//		{ RSYN,   RX,   RX,   RX,  W10, RSYN, RSYN, RSYN, SSYN, RSYN},
//		{ RSYN,   RX,   RX,   RX,  W10, RSYN, RSYN, RSYN, RSYN, SSYN}
//	};
#elif MEASURE_TYPE == PHASEMAP_TEST_6
	#define NUMBER_OF_INFRAST_NODES 6
	#define NUMBER_OF_SLOTS 6
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5
		{ RSYN,  TX1,  W10, RSYN, RSYN, RSYN},
		{ RSYN,  TX2,  W10, RSYN, RSYN, RSYN},
		{ SSYN,   RX,  W10, RSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, SSYN, RSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, SSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, RSYN, SSYN}
	};
#elif MEASURE_TYPE == PHASEMAP_TEST_4
	#define NUMBER_OF_INFRAST_NODES 4
	#define NUMBER_OF_SLOTS 4
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5
		{ RSYN,  TX1,  W10, RSYN},
		{ RSYN,  TX2,  W10, RSYN},
		{ SSYN,   RX,  W10, RSYN},
		{ RSYN,   RX,  W10, SSYN}
	};
#elif MEASURE_TYPE == PHASEMAP_TEST_5
	#define NUMBER_OF_INFRAST_NODES 5
	#define NUMBER_OF_SLOTS 5
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5
		{ RSYN,  TX1,  W10, RSYN, RSYN},
		{ RSYN,  TX2,  W10, RSYN, RSYN},
		{ SSYN,   RX,  W10, RSYN, RSYN},
		{ RSYN,   RX,  W10, SSYN, RSYN},
		{ RSYN,   RX,  W10, RSYN, SSYN}
	};
#elif MEASURE_TYPE == FIVE_MOTE_AB
	#define NUMBER_OF_INFRAST_NODES 5
	#define NUMBER_OF_SLOTS 25
	#define NUMBER_OF_RX 12
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//   0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24
		{ TX1A, TX1B, TX1A, TX1B, SSYN,  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB, TX1A, TX1B, RSYN, TX1A, TX1B,  RXA,  RXB, RSYN },
		{  RXA,  RXB, TX2A, TX2B, RSYN, TX1A, TX1B, TX1A, TX1B, SSYN,  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB, TX1A, TX1B, RSYN },
		{  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB, TX2A, TX2B, RSYN, TX1A, TX1B,  RXA,  RXB, RSYN, TX1A, TX1B, TX2A, TX2B, SSYN,  RXA,  RXB,  RXA,  RXB, RSYN },
		{  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB, TX1A, TX1B, RSYN, TX2A, TX2B,  RXA,  RXB, RSYN, TX2A, TX2B, TX2A, TX2B, SSYN },
		{ TX2A, TX2B,  RXA,  RXB, RSYN, TX2A, TX2B,  RXA,  RXB, RSYN, TX2A, TX2B, TX2A, TX2B, SSYN,  RXA,  RXB,  RXA,  RXB, RSYN,  RXA,  RXB,  RXA,  RXB, RSYN }
	};
#elif MEASURE_TYPE == PROCESSING_DEBUG
	//for processing debug it falls out of sync!
	#define NUMBER_OF_INFRAST_NODES 4
	#define NUMBER_OF_SLOTS 7
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//  0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19
		{SSYN,   RX,  W10,  W10,  DEB,  W10,  W10},
		{RSYN,  TX1,  W10,  W10, NDEB,  W10,  W10},
		{RSYN,  TX2,  W10,  W10, NDEB,  W10,  W10},
		{RSYN, NTRX,  W10,  W10, NDEB,  W10,  W10}
	};
#elif MEASURE_TYPE == LOC_TEST_9_GRID
	#define NUMBER_OF_INFRAST_NODES 12
	#define NUMBER_OF_SLOTS 20
	#define NUMBER_OF_RX 9
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//0      1      2      3      4      5      6      7      8      9      10     11     12     13     14     15     16     17     18     19
		{ RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  , RSYN , TX1  },
		{ RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  , RSYN , TX2  },
		{ SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX },
		{ RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   , RSYN , RX   },
		{ RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , RX   , RSYN , NTRX , SSYN , RX   }
	};
#elif MEASURE_TYPE == LOC_4TX_NOANCHORRX
	#define NUMBER_OF_INFRAST_NODES 13
	#define NUMBER_OF_SLOTS 16
	#define NUMBER_OF_RX 6
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{TX1,	TX1,	TX1,	NTRX,	NTRX,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{TX2,	NTRX,	NTRX,	TX1,	TX1,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	TX2,	NTRX,	TX2,	NTRX,	TX1,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	NTRX,	TX2,	NTRX,	TX2,	TX2,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN}
	};
#elif MEASURE_TYPE == LOC_3TX_NOANCHORRX
	#define NUMBER_OF_INFRAST_NODES 12
	#define NUMBER_OF_SLOTS 13
	#define NUMBER_OF_RX 3
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{TX1,	TX1,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{TX2,	NTRX,	TX1,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	TX2,	TX2,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN}
	};
#elif MEASURE_TYPE == LOC_3TX_1ANCHORRX
	#define NUMBER_OF_INFRAST_NODES 14
	#define NUMBER_OF_SLOTS 14
	#define NUMBER_OF_RX 3
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{TX1,	TX1,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{TX2,	NTRX,	TX1,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	TX2,	TX2,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN},
		{RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN}
	};
#elif MEASURE_TYPE == LOC_4TX_1ANCHORRX
	#define NUMBER_OF_INFRAST_NODES 14
	#define NUMBER_OF_SLOTS 17
	#define NUMBER_OF_RX 6
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{TX1,	TX1,	TX1,	NTRX,	NTRX,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{TX2,	NTRX,	NTRX,	TX1,	TX1,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	TX2,	NTRX,	TX2,	NTRX,	TX1,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	NTRX,	TX2,	NTRX,	TX2,	TX2,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN}
	};
#elif MEASURE_TYPE == LOC_4TX_4ANCHORRX
	#define NUMBER_OF_INFRAST_NODES 17
	#define NUMBER_OF_SLOTS 20
	#define NUMBER_OF_RX 6
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{TX1,	TX1,	TX1,	NTRX,	NTRX,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{TX2,	NTRX,	NTRX,	TX1,	TX1,	NTRX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	TX2,	NTRX,	TX2,	NTRX,	TX1,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{NTRX,	NTRX,	TX2,	NTRX,	TX2,	TX2,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN},
		{RX,	RX,	RX,	RX,	RX,	RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN}
	};
#elif MEASURE_TYPE == LOC_2TX_4ANCHORRX
	#define NUMBER_OF_INFRAST_NODES 15
	#define NUMBER_OF_SLOTS 15
	#define NUMBER_OF_RX 1
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{TX1,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{TX2,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN},
		{RX,	W100,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN}
	};
#elif MEASURE_TYPE == LOC_6TX_NOANCHOR
	#define NUMBER_OF_INFRAST_NODES 15
	#define NUMBER_OF_SLOTS 16
	#define NUMBER_OF_RX 6
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		{ RSYN, TX1, NTRX, NTRX, NTRX, NTRX, TX2, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, TX2, TX1, NTRX, NTRX, NTRX, NTRX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, NTRX, TX2, TX1, NTRX, NTRX, NTRX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, NTRX, NTRX, TX2, TX1, NTRX, NTRX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, NTRX, NTRX, NTRX, TX2, TX1, NTRX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, NTRX, NTRX, NTRX, NTRX, TX2, TX1, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN, RSYN },
		{ RSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, SSYN },
		{ SSYN, RX, RX, RX, RX, RX, RX, W100, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN, RSYN }
	}
#elif MEASURE_TYPE == MULT_RX_1
	#define NUMBER_OF_INFRAST_NODES 4
	#define NUMBER_OF_SLOTS 10
	#define NUMBER_OF_RX 2
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
		//    0     1     2     3     4     5     6     7     8     9 
		{   TX1,  TX1,  W10, RSYN,   RX,  W10, SSYN, RSYN, RSYN, RSYN },
		{   TX2,   RX,  W10, RSYN,  TX1,  W10, RSYN, SSYN, RSYN, RSYN },
		{    RX,  TX2,  W10, RSYN,  TX2,  W10, RSYN, RSYN, SSYN, RSYN },
		{    RX,   RX,  W10, SSYN,   RX,  W10, RSYN, RSYN, RSYN, SSYN }
	};

//TODO just an idea for now
// 	const_uint8_t txOther[2][NUMBER_OF_SLOTS] = {
// 		{2,3,0,0,3,0,0,0,0,0},
// 		{1,1,0,0,2,0,0,0,0,0},
// 	}
// 	
// 	const_uint8_t presetTrims[NUMBER_OF_INFRAST_NODES][NUMBER_OF_INFRAST_NODES] = {
// 		{0, 2, 0, 0},
// 		{5, 0, 2, 0},
// 		{5, 5, 0, 0},
// 		{0, 0, 0, 0},
// 	}
	#define USE_PRESET_TRIMS
	const_uint8_t presetTrims[3][NUMBER_OF_SLOTS] = {
		{2,2,0,0,0,0,0,0,0,0},
		{5,0,0,2,0,0,0,0,0,0},
		{0,5,0,5,0,0,0,0,0,0}
	};
#elif MEASURE_TYPE == SCHEDULER_AND_RSSI_LOC_TESTER
#define NUMBER_OF_INFRAST_NODES 11
#define NUMBER_OF_SLOTS 19
#define NUMBER_OF_RX 2
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
	//	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	
	{	RSYN,	TX1,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	SSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN	},
	{	RSYN,	RX,	TX1,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	SSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN	},
	{	RSYN,	RX,	TX2,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	SSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN	},
	{	RSYN,	TX2,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	TX1,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	SSYN,	RSYN,	RSYN	},
	{	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	TX1,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	SSYN,	RSYN	},
	{	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	TX2,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	SSYN	},
	{	RSYN,	NTRX,	NTRX,	SSYN,	RSYN,	RSYN,	RSYN,	RSYN,	TX2,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	TX1,	RSYN,	RSYN,	RSYN	},
	{	RSYN,	NTRX,	NTRX,	RSYN,	SSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	TX1,	RX,	RSYN,	RSYN,	RSYN	},
	{	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	SSYN,	RSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	TX2,	RX,	RSYN,	RSYN,	RSYN	},
	{	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	SSYN,	RSYN,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	TX2,	RSYN,	RSYN,	RSYN	},
	{	SSYN,	RX,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	SSYN,	RX,	RX,	RSYN,	RSYN,	RSYN,	SSYN,	RX,	RX,	RSYN,	RSYN,	RSYN	}
	};
	
	#define USE_PRESET_TRIMS
	const_uint8_t presetTrims[10][NUMBER_OF_SLOTS] = {
	//	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	
	{	0,	2,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0	},
	{	0,	0,	2,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0	},
	{	0,	0,	5,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0	},
	{	0,	5,	0,	0,	0,	0,	0,	0,	2,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0	},
	{	0,	0,	0,	0,	0,	0,	0,	0,	0,	2,	0,	0,	0,	0,	0,	0,	0,	0,	0	},
	{	0,	0,	0,	0,	0,	0,	0,	0,	0,	5,	0,	0,	0,	0,	0,	0,	0,	0,	0	},
	{	0,	0,	0,	0,	0,	0,	0,	0,	5,	0,	0,	0,	0,	0,	0,	2,	0,	0,	0	},
	{	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	2,	0,	0,	0,	0	},
	{	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	5,	0,	0,	0,	0	},
	{	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	5,	0,	0,	0	}
	};
#elif MEASURE_TYPE == COMPETITION
#define NUMBER_OF_INFRAST_NODES 11
#define NUMBER_OF_SLOTS 25
#define NUMBER_OF_RX 4
	const_uint8_t motesettings[NUMBER_OF_INFRAST_NODES][NUMBER_OF_SLOTS] = {
	//	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25
	{	RSYN,	TX1,	TX1,	RX,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	SSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN	},
{	RSYN,	TX2,	RX,	TX1,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	SSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN	},
{	RSYN,	RX,	TX2,	RX,	TX1,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	RX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	SSYN,	RSYN,	RSYN,	RSYN	},
{	RSYN,	RX,	RX,	TX2,	TX2,	RSYN,	RSYN,	RSYN,	RSYN,	TX1,	RX,	TX1,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	SSYN,	RSYN,	RSYN	},
{	RSYN,	NTRX,	RX,	RX,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	TX2,	TX1,	RX,	TX1,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	SSYN,	RSYN	},
{	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	SSYN,	RSYN,	RSYN,	RSYN,	NTRX,	TX2,	RX,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	RX,	NTRX,	TX1,	RSYN,	RSYN,	RSYN,	RSYN	},
{	RSYN,	NTRX,	NTRX,	NTRX,	RX,	RSYN,	RSYN,	RSYN,	RSYN,	RX,	RX,	TX2,	TX2,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	SSYN,	},
{	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	SSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	TX1,	RX,	TX1,	RX,	RSYN,	RSYN,	RSYN,	RSYN	},
{	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	SSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	TX2,	TX1,	RX,	TX2,	RSYN,	RSYN,	RSYN,	RSYN	},
{	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	RSYN,	RSYN,	RSYN,	RSYN,	NTRX,	NTRX,	NTRX,	NTRX,	SSYN,	RSYN,	RSYN,	RSYN,	RX,	TX2,	TX2,	RX,	RSYN,	RSYN,	RSYN,	RSYN	},
{	SSYN,	RX,	RX,	RX,	RX,	RSYN,	RSYN,	RSYN,	SSYN,	RX,	RX,	RX,	RX,	RSYN,	RSYN,	RSYN,	SSYN,	RX,	RX,	RX,	RX,	RSYN,	RSYN,	RSYN,	RSYN	}
	};
#else
	#error "Unknown MEASURE_TYPE"
#endif
#endif
