#!/bin/bash
make clean
make ucprotona
NODEID=1
while [ 1 ]
do
	echo -n "NodeID? [$NODEID]"
	read NEWNODEID
	if [ ! -z "$NEWNODEID" ]; then
		if ! [[ "$NEWNODEID" =~ ^[0-9]+$ ]]; then
			exit 0
		else
			NODEID=$NEWNODEID
		fi
	fi
	make ucprotona reinstall,$NODEID dragonjtag
	let "NODEID += 1"
done