/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../EchoRanger.h.
 */

package org.szte.wsn.downloader;

public class externalCommandConsts  {
    public static final byte CMD_SETGAIN_DUAL = 127;
    public static final short CMD_SETGAIN = 128;
    public static final byte CMD_MEASNOW = 1;
    public static final byte CMD_SETWAIT = 120;
}
