/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * /home/andris/tostrees/sztewsn/tos/lib/StreamUploaderSH/StreamUploader.h.
 */

package org.szte.wsn.downloader;

public class internalCommandConsts  {
    public static final byte CMD_ERASE = 0;
}
