/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * TestAlarm.h.
 */

public class Consts  {
	public static final short BUFFER_LEN_MIG = 480; //rfa1
//    public static final short BUFFER_LEN_MIG = 240; //rf212
}
